name: Move Kernel To Root

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  move-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Copiar contenido al root
        run: |
          shopt -s dotglob
          cp -r kernel-msm/* .
          rm -rf kernel-msm

      - name: Commit cambios
        run: |
          git add -A
          git commit -m "Move kernel to repo root" || echo "No changes"
          git push
